on:
  push:
    branches: [ "*" ]

steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
  - name: Gradle checks
    run: ./gradlew check
